# Generated by Django 5.2 on 2025-04-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Azienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestione.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prodotto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descrizione", models.TextField()),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "azienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestione.azienda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indirizzo", models.CharField(max_length=255)),
                ("città", models.CharField(max_length=100)),
                ("luogo", models.CharField(max_length=100)),
                (
                    "azienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestione.azienda",
                    ),
                ),
            ],
        ),
    ]
